// @flow
import { StyleSheet } from 'react-native';
import styles from '../../constants/styles';

const { colors, font, size } = styles;
const HEADER_HEIGHT = 180;
const HEADER_GRADIENT_HEIGHT = 85;
const TOP_RADIUS = 900;
const TOP_RADIUS_WIDTH = 150;

export default StyleSheet.create({
  container: {
    backgroundColor: colors.white,
    flex: 1,
    paddingTop: size.statusbarHeight,
  },
  section: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBlock: {
    position: 'relative',
    height: HEADER_HEIGHT,
    width: '100%',
  },
  headerGradient: {
    height: HEADER_GRADIENT_HEIGHT,
    width: '100%',
  },
  topBlockCircleWrapper: {
    position: 'absolute',
    top: 0,
    width: '100%',
    height: HEADER_GRADIENT_HEIGHT,
    overflow: 'hidden',
  },
  topBlockLeftCircle: {
    position: 'absolute',
    right: '50%',
    top: -TOP_RADIUS + HEADER_GRADIENT_HEIGHT + TOP_RADIUS_WIDTH,
    width: TOP_RADIUS,
    height: TOP_RADIUS,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: TOP_RADIUS - 50,
    borderBottomRightRadius: 0,
    borderWidth: TOP_RADIUS_WIDTH,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderColor: colors.white,
    overflow: 'hidden',
  },
  topBlockRightCircle: {
    position: 'absolute',
    left: '50%',
    top: -TOP_RADIUS + HEADER_GRADIENT_HEIGHT + TOP_RADIUS_WIDTH,
    width: TOP_RADIUS,
    height: TOP_RADIUS,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: TOP_RADIUS - 50,
    borderWidth: TOP_RADIUS_WIDTH,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: colors.white,
    overflow: 'hidden',
  },
  profileAvatarWrapper: {
    position: 'absolute',
    top: 8,
    width: 120,
    height: 120,
    borderRadius: 60,
    alignSelf: 'center',
  },
  circleImgView: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderColor: colors.white,
    alignSelf: 'center',
  },
  avatarImg: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderColor: colors.white,
    borderWidth: 5,
  },
  smallCircleTouch: {
    position: 'absolute',
    bottom: 7,
    right: 7,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderColor: colors.white,
  },
  smallCircleGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderColor: colors.white,
  },
  smallCircleImgWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderColor: colors.white,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallCircleImg: {
    width: 12,
    height: 12,
    alignSelf: 'center',
  },
  userImgNameWrapper: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    width: '100%',
  },
  userImgName: {
    textAlign: 'center',
    ...font.style.semibold,
    color: '#585858',
    fontSize: 22,
  },
  infoSection: {
    flex: 1,
    padding: 20,
    paddingTop: 10,
  },
  block: {
    flexDirection: 'row',
    height: 58,
    padding: 10,
    alignItems: 'center',
    marginVertical: 2,
    backgroundColor: colors.white,
    borderBottomColor: colors.lightGray,
    borderBottomWidth: 1,
  },
  cryoBlock: {
    flexDirection: 'column',
    height: 77,
    padding: 10,
    marginVertical: 0,
    backgroundColor: colors.white,
    borderBottomColor: colors.lightGray,
    borderBottomWidth: 1,
  },
  inputCryoBlock: {
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  selectCryoBlock: {
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  subblockLeft: {
    flex: 2,
    marginLeft: 10,
    alignItems: 'flex-start',
  },
  textLeft: {
    fontSize: font.size.small,
    color: colors.gray,
    ...font.style.medium,
  },
  subblockRight: {
    flex: 3,
    marginRight: 10,
    alignItems: 'flex-end',
  },
  textRight: {
    fontSize: font.size.normal,
    color: colors.darkGray,
    ...font.style.medium,
    textAlign: 'right',
    width: '100%',
  },
  lowSection: {
    height: 50,
    paddingBottom: 20,
    backgroundColor: colors.white,
  },
  addCryoBtn: {
    marginLeft: 25,
    marginRight: 50,
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
  },
  addCryoImg: {
    width: 12,
    height: 12,
    marginRight: 10,
  },
  addCryoTxt: {
    textAlign: 'left',
    color: '#3d74b5',
    fontSize: font.size.small,
    ...font.style.medium,
  },
  submitSection: {
    margin: 20,
    height: 70,
    paddingBottom: 20,
    width: '100%',
  },
  // forbid: {
  //   opacity: 0.4,
  // },
  submitBtn: {
    width: 160,
    height: 50,
    alignSelf: 'center',
    marginHorizontal: 'auto',
  },
  submitBtnGradient: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    // alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 80,
  },
  submitText: {
    color: colors.white,
    fontSize: font.size.normal,
    ...font.style.bold,
    textAlign: 'center',
  },
  errorMessage: {
    top: 0,
    borderBottomWidth: 1,
    borderBottomColor: styles.colors.red,
    color: colors.red,
    alignSelf: 'flex-start',
    marginLeft: 20,
    fontSize: font.size.xSmall,
    height: 17,
    marginBottom: 3,
  },
  emptyBottom: {
    height: 80,
  },
});

export const colorBlue = colors.blue;
export const colorLightBlue = colors.lightBlue;
